export const START = 'START';
export const FAIL = 'FAIL';

export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE = 'ADD_COURSE';

export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES = 'GET_COURSES';

export const GET_ONE_COURSE = 'GET_ONE_COURSE';
export const GET_ONE_COURSE_SUCCESS = 'GET_ONE_COURSE_SUCCESS';

export const UPDATE_VIDEO = 'UPDATE_VIDEO';
export const UPDATE_VIDEO_SUCCESS = 'UPDATE_VIDEO_SUCESS';

export const UPDATE_COURSE = 'UPDATE_COURSE';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

export const UPDATE_COURSE_LAST_WATCHED = 'UPDATE_COURSE_LAST_WATCHED';
export const UPDATE_COURSE_LAST_WATCHED_SUCCESS = 'UPDATE_COURSE_LAST_WATCHED_SUCCESS';
