name: Deploy to Firebase Hosting on PR

on: 
  pull_request:
    branches: [ master ]
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with: 
          envkey_REACT_APP_SERVER: ${{ secrets.REACT_APP_SERVER }}
          envkey_REACT_APP_STORAGE_SPACE: ${{ secrets.REACT_APP_STORAGE_SPACE}}
          envkey_REACT_APP_GOOGLE_API_KEY: ${{ secrets.REACT_APP_GOOGLE_API_KEY}}
          envkey_REACT_APP_GOOGLE_API_ID: ${{ secrets.REACT_APP_GOOGLE_API_ID}}
          envkey_REACT_APP_DO_STORAGE_SPACE: ${{ secrets.REACT_APP_DO_STORAGE_SPACE}}
          envkey_REACT_APP_JWPLAYER_SCRIPT: ${{ secrets.REACT_APP_JWPLAYER_SCRIPT}}
          envkey_REACT_APP_DO_BUCKET_NAME: ${{ secrets.REACT_APP_DO_BUCKET_NAME}}
          file_name: .env
      - run: npm install
      - run: npm run build --if-present

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './build'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
  merge-branch:
    needs: [Deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge staging -> uat
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: master
          github_token: ${{ github.token }}